#!/usr/bin/python
import os
import time
import json
import pytz
import requests

from math import floor
from datetime import datetime, timedelta

from xml.etree import ElementTree

MET = pytz.timezone("Europe/Amsterdam")


def get_rain():
    # r = requests.get('http://gps.buienradar.nl/getrr.php?lat=52.3796198&lon=4.7898874')
    r = requests.get('http://gps.buienradar.nl/getrr.php?lat=50.10&lon=6.93')
    rain_string = r.text
    rain_data = []
    for data in rain_string.split('\r\n'):
        if data:
            rain_amount = 10**((int(data[:3])-109)/32)
            rain_data.append({'mm_per_h': '{0:4.2f}'.format(rain_amount),
                              'mmh_num': rain_amount,
                              'time': data[4:]})

    return json.dumps(rain_data, ensure_ascii=False, indent=2).encode("utf8")


def get_weather():
    weather_dict = {}
    r = requests.get('http://xml.buienradar.nl/')
    tree = ElementTree.fromstring(r.content)

    # prediction
    for day1 in tree.iter('dag-plus1'):
        weather_dict['day1'] = {}
        for data in day1:
            weather_dict['day1'][data.tag] = data.text
    for day2 in tree.iter('dag-plus2'):
        weather_dict['day2'] = {}
        for data in day2:
            weather_dict['day2'][data.tag] = data.text
    for day3 in tree.iter('dag-plus3'):
        weather_dict['day3'] = {}
        for data in day3:
            weather_dict['day3'][data.tag] = data.text

    # current weather
    for station in tree.iter('weerstation'):
        if station.attrib['id'] == '6240':
            weather_dict['today'] = {}
            for data in station:
                weather_dict['today'][data.tag] = data.text
            break
            
    return json.dumps(weather_dict, ensure_ascii=False, indent=2).encode("utf8")


def round_down(tm):
    # from http://stackoverflow.com/questions/6933023/how-to-round-up-always-time-to-nearest-ten
    upmins = floor(float(tm.minute)/10)*10
    diffmins = upmins - tm.minute
    newtime = tm + timedelta(minutes=diffmins)
    newtime = newtime.replace(second=0, microsecond=0)
    return newtime

def get_radar():
    radar_data = []
    now = round_down(datetime.now())  # correcting for UTC?
    for minutes in xrange(-60,60,10):
        retrieve_time = now - timedelta(hours=2)+timedelta(minutes=minutes)
        actual_time = now + timedelta(minutes=minutes)
        datetimestring = retrieve_time.strftime('%Y%m%d%H%M')
        # url = 'http://buienradar.nl/image/?time={0}&type=forecastzozw&extension=png'.format(datetimestring)
        url = 'http://api.buienradar.nl/image/1.0/WebMercatorRadarNL/?t={}&ext=png'.format(datetimestring)
        r = requests.get(url)
        with file("weather_radar.png.new", "wb") as f:
            f.write(r.content)
        if minutes > 0:
            filename = "weather_radar_plus{}".format(minutes)
        elif minutes == 0:
            filename = "weather_radar_now"
        elif minutes < 0:
            filename = "weather_radar_min{}".format(-minutes)
        os.rename("weather_radar.png.new", "../{}.png".format(filename))
        radar_data.append({'time': actual_time.strftime('%a %-H:%M'),
                           'filename': filename})

    with file("weather_radar.json.new", "wb") as f:
        f.write(json.dumps(radar_data, ensure_ascii=False, indent=2).encode("utf8"))
    os.rename("weather_radar.json.new", "../weather_radar.json")


def update():
    # weather data
    with file("weather_data.json.new", "wb") as f:
        f.write(get_weather())
    os.rename("weather_data.json.new", "../weather_data.json")
    print('updated current weather data')

    # radar
    # r = requests.get('http://api.buienradar.nl/image/1.0/RadarMapNL?w=200&h=200')
    get_radar()
    print('updated current radar data')

    # rain data
    with file("weather_rain.json.new", "wb") as f:
        f.write(get_rain())
    os.rename("weather_rain.json.new", "../weather_rain.json")
    print('updated current rain data')



def main():
    while 1:
        update()
        time.sleep(180)

if __name__ == "__main__":
    main()
